AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Ataraxia-Next Local Development

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: nodejs18.x
    Environment:
      Variables:
        NODE_ENV: development
        LOG_LEVEL: debug
        DATABASE_URL: "postgresql://app_user:ChangeMe123!@dev-db-cluster.cluster-cliy2m6q8h4h.us-west-2.rds.amazonaws.com:5432/ataraxia_db?schema=ataraxia"
        COGNITO_USER_POOL_ID: "us-west-2_xeXlyFBMH"
        COGNITO_CLIENT_ID: "7ek8kg1td2ps985r21m7727q98"
        COGNITO_REGION: "us-west-2"
        FIREBASE_PROJECT_ID: "ataraxia-c150f"
        FIREBASE_CLIENT_EMAIL: "firebase-adminsdk-fbsvc@ataraxia-c150f.iam.gserviceaccount.com"
        FIREBASE_API_KEY: "AIzaSyCM2W8UE5gJekK2vV2d-UE5fVe3ZXzk1vQ"
        AUTH_PROVIDER_TYPE: "firebase"
        ENABLE_UNIVERSAL_AUTH: "true"
        JWT_SECRET: "your_jwt_secret_key_change_in_production"
        API_BASE_URL: "http://localhost:3001"
        FRONTEND_URL: "http://localhost:3000"
        ENABLE_DETAILED_ERRORS: "true"
        ENABLE_MFA: "true"
        AWS_REGION: "us-west-2"
  
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Request-ID'"
      AllowOrigin: "'*'"

Resources:
  AtaraxiaApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: local
      Name: ataraxia-next-api-local

  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: local-ataraxia-auth
      CodeUri: dist/lambdas/auth/
      Handler: handler.handler
      Description: Auth service with real production services
      Events:
        # Core auth endpoints
        Login:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/login
            Method: POST
        FirebaseLogin:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/firebase-login
            Method: POST
        Register:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/register
            Method: POST
        Confirm:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/confirm
            Method: POST
        ResendCode:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/resend-code
            Method: POST
        ForgotPassword:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/forgot-password
            Method: POST
        ResetPassword:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/reset-password
            Method: POST
        Refresh:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/refresh
            Method: POST
        Logout:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/logout
            Method: POST
        
        # MFA endpoints
        SetupTOTP:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/mfa/setup-totp
            Method: POST
        VerifyTOTP:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/mfa/verify-totp
            Method: POST
        SetupSMS:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/mfa/setup-sms
            Method: POST
        VerifySMS:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/mfa/verify-sms
            Method: POST
        SendSMSCode:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/mfa/send-sms-code
            Method: POST
        GetMFAStatus:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/mfa/status
            Method: GET
        
        # Session management
        GetActiveSessions:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/sessions/active
            Method: GET
        GetSessionAnalytics:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/sessions/analytics
            Method: GET
        InvalidateAllSessions:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/sessions/invalidate-all
            Method: POST
        TrustDevice:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/sessions/trust-device
            Method: POST
        
        # Compliance
        RecordConsent:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/compliance/consent
            Method: POST
        GetUserConsents:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/compliance/consents
            Method: GET
        GetAuditTrail:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/compliance/audit-trail
            Method: GET
        DataExportRequest:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/compliance/data-export-request
            Method: POST
        
        # Mobile registration
        MobileRegister:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/mobile/register
            Method: POST
        MobileSendPhoneCode:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/mobile/send-phone-code
            Method: POST
        MobileVerifyPhone:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/mobile/verify-phone
            Method: POST
        MobileCompleteProfile:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/mobile/complete-profile
            Method: POST
        
        # Client services
        ClientTherapists:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /client/therapists
            Method: GET
        ClientSearch:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /client/search
            Method: GET
        ClientSessions:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /client/sessions
            Method: GET
        ClientPayments:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /client/payments
            Method: GET
        BookAppointment:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /client/book-appointment
            Method: POST
        
        # Therapist status
        TherapistStatus:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/therapist/status/{id}
            Method: GET
        
        # CORS preflight
        AuthOptions:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /auth/{proxy+}
            Method: OPTIONS
        ClientOptions:
          Type: Api
          Properties:
            RestApiId: !Ref AtaraxiaApi
            Path: /client/{proxy+}
            Method: OPTIONS

Outputs:
  LocalEndpoint:
    Description: "Local development endpoint"
    Value: "http://localhost:3001"
