const fs = require('fs');
const path = require('path');

console.log('🛠️  Setting up development environment...');

const envLocalContent = `
# Local Development Environment
# Generated by setup-dev.js

NODE_ENV=development
DATABASE_URL="postgresql://postgres:postgres@localhost:5432/ataraxia_db?schema=ataraxia"
DATABASE_SCHEMA=ataraxia
AWS_REGION=us-west-2
AWS_ACCESS_KEY_ID=local_dummy_key
AWS_SECRET_ACCESS_KEY=local_dummy_secret
AUTH_PROVIDER_TYPE=firebase
FIREBASE_PROJECT_ID=ataraxia-health
API_BASE_URL=http://localhost:3010
`.trim();

const envAwsContent = `
# AWS Environment Placeholder
# Generated by setup-dev.js

NODE_ENV=production
DATABASE_URL="postgresql://user:pass@remote-host:5432/ataraxia_db?schema=ataraxia"
DATABASE_SCHEMA=ataraxia
AWS_REGION=us-west-2
`.trim();

// Write .env.local
fs.writeFileSync(path.join(__dirname, '../.env.local'), envLocalContent);
console.log('✅ Created .env.local');

// Write .env.aws (placeholder)
fs.writeFileSync(path.join(__dirname, '../.env.aws'), envAwsContent);
console.log('✅ Created .env.aws');

// Write .env (copy of local)
fs.writeFileSync(path.join(__dirname, '../.env'), envLocalContent);
console.log('✅ Created .env');

console.log('\n🎉 Environment setup complete! You can now run: npm run dev');
